### ISSUE TITLE
discuss about the project.

### ISSUE THREAD

**Issue by top-softdev** [night-fury-web/personal#1]
My skype id is live:.cid.a0993fb5fa1ac6e
I want to chat with you between 02.pm and 06.pm on next Monday with my boss. 
At that time, if you connect to me, we could talk about the job.
I want a job.

**Comment by night-fury-web** [comment]
Ok, got it.
Will connect at that time. If you want, I can create a connection now.

**Comment by night-fury-web** [comment]
Just let me know what I have to prepare beforehand including the rules I have to follow if there are.

**Comment by top-softdev** [comment]
I wanna only talk about the work.
And I expect the job.
Best regards.
See you at that time.

**Comment by night-fury-web** [comment]
Let me know your available time to discuss.
